format = "$status$all$character"


[status]
style = "fg:27"
symbol = "🔴"
format = '[\[$common_meaning$signal_name$maybe_int\]]($style) '
map_symbol = true
disabled = false

[aws]
disabled = true

[azure]
disabled = true

[battery]
disabled = true

[bun]
disabled = true

[cobol]
disabled = true

[conda]
disabled = true

[container]
disabled = true

[crystal]
disabled = true

[daml]
disabled = true

[dart]
disabled = true

[deno]
disabled = true

[docker_context]
disabled = true

[dotnet]
disabled = true

[elixir]
disabled = true

[elm]
disabled = true

[erlang]
disabled = true

[gcloud]
disabled = true

[golang]
disabled = true

[haskell]
disabled = true

[helm]
disabled = true

[java]
disabled = true

[julia]
disabled = true

[kotlin]
disabled = true

[lua]
disabled = true

[nim]
disabled = true

[nodejs]
disabled = true

[ocaml]
disabled = true

[openstack]
disabled = true

[perl]
disabled = true

[php]
disabled = true

[purescript]
disabled = true

[rlang]
disabled = true

[raku]
disabled = true

[red]
disabled = true

[scala]
disabled = true

[singularity]
disabled = true

[spack]
disabled = true

[vagrant]
disabled = true

[vlang]
disabled = true

[zig]
disabled = true
