theme = "tokyonight_storm"
# theme = "catpuccin_latte"

[editor]
bufferline = "always" # shows buffers on top of screen
true-color = true
color-modes = true
idle-timeout = 0

[editor.gutters]
layout = ["diagnostics", "spacer",  "diff"] # remove line numbers

[editor.lsp]
display-messages = true
display-inlay-hints = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.indent-guides]
render = true
character = "╎" # character every indent
skip-levels = 0

[editor.statusline]
left = ["mode", "spinner", "file-name", "file-modification-indicator"]
right = ["diagnostics", "version-control", "position"]

[editor.whitespace.render]
space = "all"

[editor.whitespace.characters]
space = "·"

[keys.normal]
X = "extend_line_above" # override capital X to expand selection to line above
C-i = "no_op"
C-o = "no_op"
"tab" = "jump_forward"
"S-tab" = "jump_backward"

[keys.normal.space]
"," = ":write" # saves changes
q = ":quit"
c = ":buffer-close" # close buffer
f = "file_picker_in_current_directory" # open current directory's file picker
F = "file_picker" # open project's file picker
E = ':pipe sed "s/dot/*/g" | sed "s/\!plus\.minus/-/g" | sed "s/plus\.minus/+/g" | kalker'

