[[language]]
name = "rust"
language-servers = [ "ra-multiplex" ]

[language-server.ra-multiplex]
command = "ra-multiplex"

[language-server.ra-multiplex.config.check]
command = "clippy"

[[language]]
name = "typescript"
indent = { tab-width = 4, unit = "    " }

[language-server.typst]
command = "tinymist"
# command = "typst-lsp"
config = { formatterMode = "typstyle", formatterPrintWidth = 80, exportPdf = "never" }

# [language-server.typst.config]
# exportPdf = "never"

[language-server.harper-ls]
command = "harper-ls"
args = ["--stdio"]

[[language]]
name = "typst"
scope = "source.typst"
injection-regex = "^typ(st)?$"
file-types = ["typ"]
comment-token = "//"
roots = []
language-servers = ["harper-ls", "typst"]
indent = { tab-width = 2, unit = "  " }
# formatter = { command = "typstfmt", args = ["--output", "-"] }
auto-format = true

[language.auto-pairs]
'(' = ')'
'{' = '}'
'[' = ']'
'"' = '"'
'`' = '`'
'$' = '$'

[[language]]
name = "numbat"
scope = "source.numbat"
file-types = ["numbat"]
comment-token = "#"
grammar = "numbat"

[[grammar]]
name = "numbat"
source = { git = "https://github.com/irevoire/tree-sitter-numbat", rev = "b4dd180397cad0638abbf18b54e354ea43276f46" }
