#!/usr/bin/env nu

$env.PATH = [
    # '/usr/local/Caskroom/miniforge/base/condabin',
    '/Applications/LilyPond.app/Contents/Resources/bin',
    $"($env.HOME)/.cargo/bin",
    $"($env.HOME)/.elan/bin",
    $"($env.HOME)/.juliaup/bin",
    $"($env.HOME)/.wasmtime/bin",
    $"($env.HOME)/.local/bin",
    # '/Users/francischua/thomas_scripts',
    '/usr/local/go/bin',
    '/Users/francischua/go/bin',
    '/Users/francischua/gitprojects/CS140E/cs140e-25win/bin',
    # '/Applications/Wine Crossover.app/Contents/Resources/wine/bin',
    # '/Users/francischua/gitutils/wabt/build',
    '/Library/TeX/texbin',
    '/opt/homebrew/opt/postgresql@15/bin',
    '/Library/Frameworks/Maple.framework/Versions/2022/bin',
    '/usr/local/opt/ruby/bin',
    # '/Users/francischua/gitutils/executables/shellscript',
    '/opt/homebrew/Cellar/llvm/16.0.6/bin',
    '/Users/francischua/.ghcup/bin',
    '/Users/francischua/gitutils/executables',
    '/Users/francischua/.deno/bin/',
    '/opt/homebrew/Cellar/ruby/3.4.7/bin/',
    '/Users/francischua/.gem/ruby/3.4.0/bin',
    # '/Users/francischua/Library/Python/3.9/bin',
    # '/usr/local/texlive/2022/bin/universal-darwin',
    $"($env.HOME)/bin",
    '/opt/homebrew/bin/',
    '/usr/local/bin',
    '/usr/bin',
    '/opt/homebrew/opt/binutils/bin/',
    '/bin',
    '/usr/sbin',
    '/sbin',
]
